parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     riktamBlog
    database_user:     root
    database_password: 

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       noreply@blog.com
    mailer_password:   

    locale:            en
    secret:            bd6ef9e8153c1a3cab6f0602e25f76f5
