#venu bundles
venu_admin:
    resource: "@VenuAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

VenuAdminBundle:
    resource: "@VenuAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


VenuBlogBundle:
    resource: "@VenuBlogBundle/Resources/config/routing.yml"
    prefix:   /
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /apidoc
    
venu_api_public:
    resource: Venu\ApiBundle\Controller\SecurityController
    type: rest

venu_api_posts:
    resource: Venu\ApiBundle\Controller\BlogController
    prefix: /api
    type: rest
    
#fos user bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
