security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512 #sha512

    firewalls:  
        fos_secured:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        wsse_secured:
            pattern:   ^/api/(?!token|public|resend|doc|blog\/create).*
            stateless:    true
            wsse:
                nonce_dir: null
                lifetime: 1800
                provider: fos_userbundle
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/comment/*, role: ROLE_USER }

    role_hierarchy:
        ROLE_USER:      ROLE_USER
        ROLE_API_USER:     ROLE_API_USER        
        ROLE_ADMIN:    [ROLE_USER, ROLE_API_USER]
