security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
        #api_http_basic:
        #    memory:
        #        users:
        #            iphone:  { password: welcome, roles: 'ROLE_API_USER' }
        #            flash: { password: welcome, roles: 'ROLE_API_USER' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512 #sha512

    firewalls:
        #api_secured:
        #    pattern:    ^/api/.*
        #    anonymous: false
        #    provider: api_http_basic
        #    http_basic: ~
            
        #fos_secured:
        #    pattern: ^/
        #    form_login:
        #        provider: fos_userbundle
        #        csrf_provider: form.csrf_provider
        #    logout:       true
        #    anonymous:    true

        wsse_secured:
            pattern:   ^/api/(?!token|public|resend|doc).*
            stateless:    true
            wsse:
                nonce_dir: null
                lifetime: 1800
                provider: fos_userbundle
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_USER:      ROLE_USER
        ROLE_API_USER:     ROLE_API_USER        
        ROLE_ADMIN:    [ROLE_USER, ROLE_API_USER]
