VenuBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: VenuBlogBundle:Page:index }
    requirements:
        _method:  GET
        
VenuBlogBundle_about:
    pattern:  /about
    defaults: { _controller: VenuBlogBundle:Page:about }
    requirements:
        _method:  GET
        
VenuBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: VenuBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

VenuBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: VenuBlogBundle:Comment:create }
    requirements:
        _method:  POST
        id: \d+
        
VenuBlogBundle_blog_like:
    pattern:  /like/add/{id}
    defaults: { _controller: VenuBlogBundle:Like:add }
    requirements:
        _method:  GET|POST
        id: \d+

VenuBlogBundle_blog_dislike:
    pattern:  /like/delete/{id}
    defaults: { _controller: VenuBlogBundle:Like:delete }
    requirements:
        _method:  GET
        id: \d+